### ISSUE TITLE
Decide whether to remove the Internal tab

### ISSUE THREAD

**Issue by ianhinder** [EinsteinToolkit/www.cactuscode.org#1]
This links to https://wiki.cct.lsu.edu/frameworks.  It probably doesn't belong on cactuscode.org.

**Comment by rhaas80** [comment]
Since the new page is static and in a public repo, having a "private" internal part does not seem to make much sense.

**Comment by rhaas80** [comment]
I removed Internal in favor of Home (at the very left) in ff7bf82
