### ISSUE TITLE
Contact page mailing list link points to a nonexistent PHP file

### ISSUE THREAD

**Issue by ianhinder** [EinsteinToolkit/www.cactuscode.org#12]

**Comment by rhaas80** [comment]
There does seem to be a markdown file with the content of as of d88cec3 (Thu Apr 30) which is the same day this issue was created. Is this still an issue?

**Comment by rhaas80** [comment]
Ok. The non-existing link was on the `about/mailinglists` page namely the one for `patches` which had the wrong directory given. Fixed in fd7d44c.
