### ISSUE TITLE
Decide what to do about all the files in "global"

### ISSUE THREAD

**Issue by ianhinder** [EinsteinToolkit/www.cactuscode.org#13]

**Comment by rhaas80** [comment]
* all php files in the main directory should go away
* `tools/ls.php` can be removed (was used for news)
* GitHub lets one have custom error pages: https://docs.github.com/en/github/working-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site so the ones in `error` could be converted to markdown
* `images` contains only image files and the ones no longer used could be removed

**Comment by rhaas80** [comment]
Error pages converted for GtiHub in 4ac3da1.

**Comment by rhaas80** [comment]
most unused files were removed in 1c2b7dff669daf983d5cee313e7820480152cd22
