### ISSUE TITLE
Link to "Live wavetoy demo" doesn't work

### ISSUE THREAD

**Issue by ianhinder** [EinsteinToolkit/www.cactuscode.org#17]

**Comment by stevenrbrandt** [comment]
Is this needed, or can we remove it?

**Comment by rhaas80** [comment]
We could point to the tutorial server instead. WaveToy as used in the demo is quick to compile. I am not sure that we need to have a perpetually running wavetoy.

Since the code produces jpeg files one can even watch them in jupyter.

**Comment by rhaas80** [comment]
This link is dead already on the PHP based server: http://cactuscode.org:8080/ and my guess would be that it has not been working for a long time. Since there were no complaints I would think that at least the "live" part can be removed.

**Comment by stevenrbrandt** [comment]
I think this is removed in test.cactuscode.org now.
