### ISSUE TITLE
Fix "Thorn guides" on documentation page

### ISSUE THREAD

**Issue by ianhinder** [EinsteinToolkit/www.cactuscode.org#4]

**Comment by rhaas80** [comment]
Can be fixed by pointing to: http://einsteintoolkit.org/documentation/ThornGuide.php

**Comment by ianhinder** [comment]
I think it's better to have just the Cactus thorns, not the Einstein Toolkit ones. Implemented in b1b760987ff3c63ce2ba6b0452565ad1139ebfa2.

**Comment by rhaas80** [comment]
Using liquid is much nicer than relying on External PHP code. Thanks for the extra work!
