### ISSUE TITLE
Fix "Overview of thorn README files" on Documentation page

### ISSUE THREAD

**Issue by ianhinder** [EinsteinToolkit/www.cactuscode.org#5]

**Comment by rhaas80** [comment]
I added a javascript version in git hash [67b57ab](https://github.com/EinsteinToolkit/cactuscode.org/commits/67b57abcd8d2346f42284ccab5690bbe9d409d4b) "documentation: produce list of Readme files using javascript" of [cactuscode.org](https://github.com/EinsteinToolkit/cactuscode.org)

**Comment by rhaas80** [comment]
The Javascript solution seems workable for now. If we ever automate creating and updating the documtenttion files based on a thornlist then instead of using Javascript we should most likely just store the relevant information in a yaml file for Jekyll to use same as for the news items.
