### ISSUE TITLE
The News section is empty

### ISSUE THREAD

**Issue by ianhinder** [EinsteinToolkit/www.cactuscode.org#7]
This probably has some dynamic content.  We can set up news stories as Jekyll/Liquid collections.

**Comment by rhaas80** [comment]
As of  git hash [abd61d1](https://github.com/EinsteinToolkit/cactuscode.org/commits/abd61d19717440ea436f195ef6f5ae608de8c6d9) "news: construct from data in yaml file" of [cactuscode.org](https://github.com/EinsteinToolkit/cactuscode.org) this is constructed from yaml data in _data/new.yml
